# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e446d73ada9c3f905d0ed763c13c344cba4ab7508ef7f5c0e9b27242fe60884a5a04150971c254a9a6bbb0139c3192d20540869733d445896f924ced5c96fd9

test:
  secret_key_base: c5bf219602daa2b66c1f11d65dd1bfb52f039445cca4cca016fab66d1d16c999d3a18acefbc586286657596b7cffff000733294aa4fa8b5d173d4eb66106077c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
